sudo: required
services:
  - docker

before_install:
  - sudo apt-get update

before_script:
  - docker pull openvinoincluit/openvino:driver || true
script:
  - docker run --name openvinocont -t -d openvinoincluit/openvino:driver
  - docker exec openvinocont git clone https://github.com/incluit/OpenVino-Driver-Behaviour
  - docker exec openvinocont bash -c 'source /opt/intel/openvino/bin/setupvars.sh && cd /app/OpenVino-Driver-Behaviour && mkdir build && cd build && source /app/OpenVino-Driver-Behaviour/scripts/setupenv.sh && cmake .. && make'

after_script:
  - docker images
